# Conclusion

The main takeaways of our exploration start with the process of beginning a data science visualization project. We were able to see different breakdown of player data and season performance. The graphs visually entice the audience and provide a powerful understanding about how teams performed in different years in a professional basketball league. This approach to portraying NBA data makes observing the patterns we noticed more accessible to a wider audience. Overall, we had a lot of success in uncovering interesting trends through our visualizations.

Throughout our exploration, we tended to focus on the "bubble" to understand if gameplay changed during this unusual period of NBA history. In many cases, we noticed interesting trends during the bubble relative to the surrounding years. It would be interesting to better understand the causes behind these patterns. It's worth noting that this was not universally true; in some cases we noticed no discernible change during the bubble.

## Lessons learned

One lesson learned was that gathering the right data takes the right questions and right primary sources. The right kinds of color and visualizations do really make visualizations more accessible and successful. Audiences can be pulled in to a really good story and the visualization can tell that story if it fits or makes sense with the data.

We also learned that extracting data is not always easy. Indeed, in our case it took a significant amount of time for some of our team members. In general, as we go forward as data scientists, this is an important lesson to keep in mind: real world data is messy and getting good data might be the hardest part of some projects.

## Future work

For our seasonal data, we would love to pull a complete history of all seasons' data. This would be a lengthy amount considering the NBA extends back to 100s of years ago. Also, the team data would look very different as there were different teams and league points can't be compared because of the size of the league back then and now. It would be interesting to explore additional variables such as coach impact and injuries. These variables might be able to provide a powerful association for how a team performs in the league and in post-season/playoffs. 

In regards to shot data, in the future we'd like to pull data for all players instead of only the top 100. With enough time and resources, this should be possible. Doing so would roughly double our dataset, so hopefully the trends we've observed here would hold. This is the main limitation of the analysis we did on shot data.
