--- 
title: "NBA Project"
author: "Yunchen Jiang, Akshay Iyengar, Conor Ryan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We chose to explore various components of NBA data because we all have a common interest in the NBA. For any readers unfamiliar, the NBA is the National Basketball Association and is the highest level of professional basketball played in North America. As a sport, basketball provides a rich opportunity for data collection, which is why we were interested in seeing if we could create interesting visualizations from it. All parts of the sport -- from the many different teams and players, to the many different head-to-head games throughout the season, to the granular play-by-play shooting activity -- provide potentially interesting areas for us to explore within data.

One important phenomenon to note was the "bubble" period created by COVID-19 during the 2020 season. This was the NBA's solution to enable the continuation of the season despite the pandemic; it involved a bio-secured facility in Florida where players were silo'd from the world while they played games to finish the season. In much of our analysis, we focused on this period to try and see if there were any interesting trends that came about during the bubble period.