# Proposal

## Research topic
Our research topic generally deals with NBA player/game data. Since that is such a big area, we will focus our attention in particular to more recent years. If needed, we may also later focus on particular teams to make the task manageable and allow us to gain more interesting insights.

The primary topic we intend to explore is if there have been any significant shifts in basketball patterns due to COVID. This will involve considering three periods: pre, during (the "bubble" phenomenon), and post. We'd like to understand if any players' stats in particular shifted dramatically across these periods. It would also be interesting to understand if the significant "shifts" across all players were typical over such a period, or if the "bubble" might have exacerbated these trends. Another topic we'd like to explore is if any fundamentals of gameplay changed across these periods. For example, did people start shooting more three-pointers or half-court-shots? Did free-throw accuracy change noticeably?

One complication in all of this will be trying to isolate normal trends from those created by COVID. For example, if we observe any variation, is that variation within a reasonable expectation historically in the NBA, or does it seem like a true outlier potentially attributable to the COVID period?

## Data availability
There are a lot of places to get basketball stats from, so we will consider several sources and ultimately focus on the one that works best in practice for the questions we're trying to answer.

Various sports news sites, like ESPN, CBS, etc. will be a good starting point. The data from such sources is typically collected by the organizations themselves. We can trust these with relative ease, as these are good sources who put their reputation on the line by reporting with these statistics. Data is updated in near real time, so we will look to collect their historical data and "lock" it in time. These sites typically do not make their data available in any particularly friendly way, so we will need to web scrape these pages, download them in HTML format, and extract tabular format from them with R. We will also need to be careful when getting the data and not violate their privacy policies. There are no known issues with this data currently.

There are also many other external organizations that aggregate data which we can try and use. Basketball-reference.com (run by Sports-reference.com) will be one such valuable resource to us. Their data is extremely verbose, potentially moreso than that provided by news organizations, so it may end up being more useful. One thing worth considering is that they serve as an aggregator of data, meaning they combine proprietary data from many other sources, so although they do not do collection themselves, they may also be the only way of retrieving the data in this format. They do not name their upstream vendors. We will look to do more research and try and get as close to the data collectors as possible, but it's feasible they are the best option simply because of licensing agreements and the obviously strict nature of professional sports statistics. Their [Terms of Use](https://www.sports-reference.com/termsofuse.html) makes clear that they allow anyone to download and use their data as long as a reference is provided and the data is not used to compete against them as a provider. They restrict web-scraping to twenty requests per minute, so we will remain mindful of this. Most of their statistics pages also make it relatively easy to just download a CSV, so to "lock" our data in place and avoid any scraping issues, we will seek to manually download their data where feasible. This will then be simple enough to import into R. There are no known issues with their data. They claim to respond to all email, so if we have issues, we can try and contact them (although they request a week to respond).

Bibliography:
[Wikipedia](https://en.m.wikipedia.org/wiki/2020_NBA_Bubble)

[StatMuse](https://www.statmuse.com/nba/ask/best-offensive-rating-team-list-in-the-bubble)

[ESPN](https://www.espn.com/nba/standings/_/season/2020)

[Basketball-Reference](https://www.basketball-reference.com/)
